### ISSUE TITLE
Pristupnost

### ISSUE THREAD

**Issue by mandik-spsejecna-cz** [sochurek/kevizb.cz#1]
Dobry den, neslo by odstranit chyby pristupnosti podle https://fae.disability.illinois.edu/pages/1847acda62042db3/rc/all/page/1/ ?

**Comment by sochurek** [comment]
Dobrý den, všechny violations byly odstaněny. https://fae.disability.illinois.edu/pages/1847b02fe7b0aff1/rc/all/page/1/

**Comment by mandik-spsejecna-cz** [comment]
thx
